spring.application.name=calculatorhub

# Server
server.port=8080

# MySQL DB
spring.datasource.url=jdbc:mysql://localhost:3306/calculatorhub
spring.datasource.username=root
spring.datasource.password=1234

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Fix warning
spring.jpa.open-in-view=false